import fs from 'fs';
import path, { dirname } from 'path';
import { fileURLToPath } from 'url';
import {
  SuspendAction,
  runMigration,
  updateMigrationTable,
} from '@min-two/actions-iso';

const ensureSqlExists = () => {
  if (fs.existsSync('../migrations/sql')) {
    return true;
  } else {
    return false;
  }
};

function getMigrationFileName() {
  const timestamp = Date.now(); // Get current timestamp
  const uniqueIdentifier = Math.random().toString(20).substring(2, 7); // Generate a random unique identifier
  return `adminGen_suspend-business_stores.store_${timestamp}_${uniqueIdentifier}.sql`;
}

function getMigrationDeatils(id: string, adminName: string) {
  const migrationName = getMigrationFileName();
  const adminLine = `-- Auto-generated by Admin ${adminName}\n`;
  const migrationContent = `-- Migration ${'suspend-business'} action on table stores.store\n`;

  const migrationContentWithUpdate = `
  ${adminLine} ${migrationContent}
    UPDATE stores.store
    SET is_pending = true
    WHERE sid = '${id}';`;

  // Return migration content as a string
  return {
    sqlName: migrationName,
    sqlContents: migrationContentWithUpdate,
  };
}

// Not moved the iso because of direcory dependencies
function uploadMigration(contents: string, name: string) {
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);

  const directory = path.join(__dirname, '..', '..', '..', 'migrations', 'sql');
  const where = path.join(directory, name);

  fs.writeFile(where, contents, (err) => {
    if (err) {
      console.error('Error with admin action', err);
      throw new Error('Error writing file');
    }
  });
  return where;
}

async function deleteFile(filePath: string) {
  try {
    await fs.promises.unlink(filePath);
  } catch (err) {
    console.error(`Error deleting file ${filePath}:`, err);
  }
}

export const handleSuspendBusiness = async (suspendDetails: SuspendAction) => {
  const hasSqlDirectory = ensureSqlExists();
  if (hasSqlDirectory) {
    const deatils = getMigrationDeatils(
      suspendDetails.id,
      suspendDetails.adminName
    );
    //   location of file
    const where = uploadMigration(deatils.sqlContents, deatils.sqlName);
    try {
      await runMigration(deatils.sqlContents);
      await updateMigrationTable(deatils.sqlName);
    } catch (e) {
      deleteFile(where);
      throw new Error('Error with migration process');
    }
  } else {
    throw new Error('Sql directory does not exist');
  }
};
