
                -- Auto-generated by Admin Deontae
 -- Migration suspension-business action on table stores.store

                UPDATE stores.store
                SET is_pending = true
                WHERE sid = '69c6514f-5b93-4304-8fdb-1d5113423404';